config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'events/index', to: 'events#index'
  get 'events/secret'
  root to: "events#index"
  get 'events/new', to: 'events#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :users, through: :attendances
    belongs_to :admin, class_name: "User"
    validates :start_date, presence: true
    validates :duration, presence: true
    validates :title, presence: true, length: {minimum: 5, maximum: 140}
    validates :description, presence: true, length: {minimum: 20, maximum: 1000}
    validates :price, presence: true
    validates_numericality_of :price,
    :greater_than => 1.0,
    :less_than => 1000.0
    validates :location, presence: true
   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :attendances
    has_many :events, through: :attendances
    has_many :organised_events, foreign_key: 'admin_id', class_name: "Event"
    after_create :welcome_send

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def secret
  end

  def new
  end
end

app/controllers/events_new_controller.rb
class EventsNewController < ApplicationController
    def new
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/events_new_helper.rb
module EventsNewHelper
end

app/views/events/index.html.erb
<h1>Bienvenue sur EventBrite</h1>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", events_secret_path %>
    </li>

    <li>
      <%= link_to "Modifier ton email ou ton mot de passe", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Se connecter", new_user_session_path %>
    </li>

    <li>
      <%= link_to "S'inscrire", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/events/new.html.erb
<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEvent4">Event title</label>
      <input type="text" class="form-control" id="inputEvent4" placeholder="Title">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Description</label>
      <input type="text" class="form-control" id="inputPassword4" placeholder="Description">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Price</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="€">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Duration</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="days">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">Adress</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        <option>...</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>

app/views/events/secret.html.erb
<h1>Events#secret</h1>
<p>Find me in app/views/events/secret.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">EventBrite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/events/index">Accueil <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/events/new">Créer Event</a>
        </li> 

        <%if session[:user_id]%>
        <%= link_to "Mon profil", user_session_path(session[:user_id]) %>
        <%= link_to "Se déconnecter", user_session_path(session.id), method: :delete %>
      <% else %>
        <div class="dropdown">
          <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            S'inscrire / Se connecter
          </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>  
            <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %></div>
        </div>
      <% end %>
      </ul>
      </div>
    </nav>
  </header>
    
</div>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    
  </div>
</div>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= notice %></p>
  
    </body>
</html>